### ISSUE TITLE
Empty doc block leads to dublication of preceding comments

### ISSUE THREAD

**Issue by powtac** [rectorphp/rector#4191]
# Bug Report

See https://getrector.org/demo/d8a61030-ec46-4814-ace1-89b71f9b81a5

Code with empty doc block like 

```
/**
 */
class a {}
```

will have all preceding comments of this doc block be dublicated. 

```
<?php

// First Comment

// Second Comment

/**
 */
class a {}
```

becomes

```
<?php

// First Comment
// First Comment
// Second Comment
// Second Comment

/**
 */
class a {}
```

The rule itself does not matter (tested with SetList::CODE_QUALITY), as soon there is some change in the file, this will happen. Tested with Rector 0.8.x-dev@172653b (prefixed)

## Background

This is a very common comment pattern in old PHP source files, see this example: https://getrector.org/demo/b25ea5bc-de7d-43b0-81bc-89fe5f391972#result (similar to my very initial problem.)

## Expected Behaviour

PHP source code comments should not be dublicated.

**Comment by samsonasik** [comment]
seems already fixed in latest master https://getrector.org/demo/a25a5db5-18f9-4f31-b2d2-61e82cb83757#result

**Comment by TomasVotruba** [comment]
@samsonasik Thank you taking care of these old issues

**Comment by powtac** [comment]
It is not fixed in 0.9.0.

**Comment by TomasVotruba** [comment]
Indeed, the demo link was out of date because I've cleaned up the database. My appologies.

Here is correct link that shows it's still a problem: https://getrector.org/demo/9f444d47-e79f-4f34-a711-995c2488683e

**Comment by samsonasik** [comment]
The issue seems not in the rule, but in the post-rector somewhere, as changing service keep duplicating comment.

**Comment by powtac** [comment]
It might be a good idea to have a dummy rector rule that can be applied for cases like this to make sure it is not caused by a rector rule itself but from the rector framework of third-party.

**Comment by powtac** [comment]
This still does not work as expected when running for example the SetList::PHP_74 and not only DEAD_CODE.

**Comment by TomasVotruba** [comment]
@powtac Could you send another test fixture here?
https://github.com/rectorphp/rector/pull/5106/files?file-filters%5B%5D=.php#diff-7a36ba9719f9097d031694783f7d041d97b2ce0530e76ac45a783f0028497ba7
