### ISSUE TITLE
How to debug errors?

### ISSUE THREAD

**Issue by splitbrain** [rectorphp/rector#8396]
Since upgrading to rector 0.19 my rector action no longer succeeds on github. When running the same call on my local system (using the same versions) everything works as expected.

I am a bit stuck on how to figure out what exactly is going on. Even running rector with `--debug` does not produce any additional error messages. All I get is the following:

```
Error: ] Could not process                                                      
         "/home/runner/.composer/vendor/bin/_tools/rector-ce722f33142d690bb972ad
         379fe7f6391900026941ae9cbebaec976fbd8d365b/vendor/rector/rector/vendor/
         symplify/easy-parallel/src/ValueObject/ParallelProcess.php" file, due  
         to:                                                                    
         "Child process timed out after 60 seconds". On line: 108               
Error: ] Could not process some files, due to:                                  
         "Reached system errors count limit of 50, exiting...".                 
Error: Process completed with exit code 1.
```

* How do I find out which child process timed out and what did it do?
* What exactly are those 50 system errors?

**Comment by samsonasik** [comment]
Since rector 0.19, the timeout is 60 second, you can update to 120 from previous config:

```php
$rectorConfig->parallel(120, 16, 15);
```

**Comment by splitbrain** [comment]
Ah tuning these parameters (using 120,16,10) did indeed fix the issue for.

The question remains: what are those 50 system errors? Just follow-up errors from a single timeout? Or 50 processes timing out? The errors are a bit opaque.

**Comment by TomasVotruba** [comment]
This might be due to reason Github Action does only suport 2-3 parallel jobs that take longer.

Still there might be some miss-configuration, e.g. using Rector on generated files, templates etc., or leaking rules/files.

**Comment by samsonasik** [comment]
@splitbrain the error message may can be improved, could you create a PR to rector-src? Thank you.

**Comment by splitbrain** [comment]
:-) No I can't because I don't know what's going on and have more than enough to do on my own open source projects.

Anyway this issue is solved (enough) for me to get on with my own code. Thanks again for your quick help :+1:

**Comment by TomasVotruba** [comment]
This would require checking the `rector.php` and look for possible memory leaks in your project file structure. Not an easy path :)

I'm thinking what `--debug` could do is disabling parallel run, as that's how PHPStan handles it. That way Rector would not show `internal error` but the particular one. @samsonasik What do you think?

**Comment by samsonasik** [comment]
On big projects, disabling parallel will be very slow, so it seems not the solution.

The other area may be improved, like extract `PathSkipper` service as dedicated service, (not as `SkipVoter`) and verify before create `new File($filePath, Filesystem::read())` usage when it clear that the path is skipped.

**Comment by TomasVotruba** [comment]
> On big projects, disabling parallel will be very slow, so it seems not the solution.

That would only happen when `--debug` is added, so we can see the errors directly. With parallel they're hidden behind "system error".

**Comment by samsonasik** [comment]
That's not hidden if process crash, eg: throw `ShouldNotHappenException`, error will still shown.

process timeout seems due to wait for other process picking up, that mostly happen on CI.

**Comment by staabm** [comment]
> This might be due to reason Github Action does only suport 2-3 parallel jobs that take longer.

the problem is with doubled processes we need the double amount of ram.
we are using more ram then the runner has, which makes it swap and every memory access gets super slow.

in addition the free runner has only 2 CPUs, which means we the OS needs to schedule 32 worker processes over 2 CPUs.

this constallation is prone to errors

**Comment by lugosium** [comment]
Also got this error, rector 0.19 is slower compared to 0.18.

**Comment by samsonasik** [comment]
@lugosium I applied some performance improvement on latest `dev-main`, you may still need `timeout` and `jobs` configure if you have limited resource tho, eg: on CI

**Comment by lugosium** [comment]
thanks @samsonasik, i tried and same results. Macbook is burning and very slow.

**Comment by samsonasik** [comment]
@lugosium is changing parallel config solve the issue?

```php
$rectorConfig->parallel(120, 16, 15);
```

If no, you may can help us to find possible bottleneck in the diff :) https://github.com/rectorphp/rector-src/compare/0.18.13...main
