### ISSUE TITLE
FunctionFirstClassCallableRector/FunctionLikeToFirstClassCallableRector dangerously assumes arguments are the same

### ISSUE THREAD

**Issue by uncaught** [rectorphp/rector#9465]
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | 2.2.5             |

FunctionFirstClassCallableRector and FunctionLikeToFirstClassCallableRector massively broke our code/tests.

I think they are dangerous and should not be enabled by default. There is no guarantee that the caller will provide the arguments that you expect in the callable.

E.g.:

```php
function foo(int $num, ?string $str = null): void;

function bar(callable $fn): void {
  $fn(42, 84); //calls with two integers!
}

bar(fn($num) => foo($num)); //works, $num is an integer
bar(foo(...)); //will throw an error!!! the second argument is supposed to be a string, but is int!
```

## Minimal PHP Code Causing Issue

In one of our broken code cases, this was changed by rector:

```diff
  public function get(string $ident): int {
    $key = $this->getLastModifiedUnixCacheKey($ident);

-    return $this->cache->get($key, fn() => time());
+    return $this->cache->get($key, time(...));
  }
```

> ArgumentCountError: time() expects exactly 0 arguments, 2 given

## Expected Behaviour

I would recommend to disable these rules entirely or at least make them opt-in!

**Comment by samsonasik** [comment]
That seems already resolved in latest dev-main, see https://getrector.com/demo/ef90b955-bd06-46bc-87d5-f23f9df13704

**Comment by uncaught** [comment]
Thanks, but how does it know? The callable could go anywhere. You can hardly detect the usages if they are anywhere in the code.

**Comment by samsonasik** [comment]
It check by ast resolver, locate its target, and check the usage as invokable calls, we are collecting use cases, if reasonable and fixable, we can fix it, like your use case that already fixed :)

**Comment by TomasVotruba** [comment]
@uncaught I've just tagged https://github.com/rectorphp/rector/releases/tag/2.2.6
Give it a go and let us know it the issue still persists

**Comment by uncaught** [comment]
> [@uncaught](https://github.com/uncaught) I've just tagged https://github.com/rectorphp/rector/releases/tag/2.2.6 Give it a go and let us know it the issue still persists

Thank you, but it's still modifying the code to `return $this->cache->get($key, time(...));` while cache adapter callback has a signature like `(CacheItem $item, bool &$save)`.

However, all the other places seem to be okay now. It's just this `time(...)` that's still broken.

**Comment by uncaught** [comment]
Here is the relevant part of the class if you like:

```php
<?php

declare(strict_types=1);

namespace Foo;

use Symfony\Contracts\Cache\CacheInterface;

class Foo {
  public function __construct(
    private readonly CacheInterface $cache,
  ) {
  }

  public function get(): int {
    return $this->cache->get('bar', fn() => time());
  }
}
```

**Comment by TomasVotruba** [comment]
@uncaught  Thanks for feedback 👍 

Can you isolate it from Symfony code and create minimal reproducer on
https://getrector.com/demo ?

I'll look into fix here

**Comment by uncaught** [comment]
Sure: https://getrector.com/demo/75a7f014-74fa-4da2-b853-f7d65ad1aa3c

I'd be interested in how you can detect this though. Scanning the annotations could potentially be misleading.

**Comment by samsonasik** [comment]
I will look into it, as new arg should be skipped as can fill property to use later.
